name: Helwan Stream Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install System Tools (Ubuntu Alternative)
      run: |
        sudo apt-get update
        # بنثبت الأدوات اللي البرنامج محتاجها بس بنظام Ubuntu عشان الـ Action ينجح
        sudo apt-get install -y mpv ffmpeg aria2 libpulse0

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        # هنا بنسطب المكتبات البرمجية فقط
        find . -name "requirements.txt" -exec pip install -r {} +

    - name: Check Main Script
      run: |
        # التأكد من أن الكود سليم برمجياً
        find . -name "main.py" -exec python -m py_compile {} +
