name: Arch Linux Package Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # هنا بنقول لجيت هاب: افتح "أرش" جوه "أوبونتو"
    container:
      image: archlinux:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup System & Build
      run: |
        pacman -Syu --noconfirm base-devel binutils
        # صناعة الحزمة تتطلب مستخدم غير الـ Root
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        sudo -u builder makepkg -s --noconfirm

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hel-stream-package
        path: "*.pkg.tar.zst"
